name: build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      # - uses: actions/checkout@v2
      # - name: Pushes test file
      #   uses: asxing/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source_file: 'test1111'
      #     destination_repo: 'asxing/test2'
      #     destination_folder: 'test2'
      #     user_email: 'holddie@163.com'
      #     user_name: 'Asxing'
      #     destination_branch: 'main1'
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: asxing/test2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main1"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
