name: build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@v2
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'test1'
          destination_repo: 'asxing/test1'
          destination_folder: 'test2'
          user_email: 'asxingyang@gmail.com'
          user_name: 'asxing'
          destination_branch: 'main'
